name: example
description: A sample command-line demostration of the Dart onboard_sdk package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  onboard_sdk:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
